CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17
TARGET = planificador

all: $(TARGET)

$(TARGET): planificador.cpp
        $(CXX) $(CXXFLAGS) planificador.cpp -o $(TARGET)

clean:
        rm -f $(TARGET)
